import type { AppCommandId } from "./commands";

export const SEARCH_BROWSE_COMMAND_IDS = [
  "continue",
  "filters",
  "recommendation",
  "random",
  "surprise",
  "calendar",
  "bookmark",
  "follow",
  "watchlist",
  "playlist",
  "stats",
  "sync",
  "library",
  "downloads",
  "notifications",
  "history",
  "download",
  "details",
  "setup",
  "settings",
  "trending",
  "toggle-mode",
  "provider",
  "diagnostics",
  "clear-cache",
  "reset-provider-health",
  "export-diagnostics",
  "help",
  "menu",
  "about",
  "quit",
] as const satisfies readonly AppCommandId[];
