import type { AppCommandId } from "./commands";

export const SEARCH_BROWSE_COMMAND_IDS = [
  "continue",
  "filters",
  "recommendation",
  "calendar",
  "bookmark",
  "follow",
  "watchlist",
  "playlists",
  "up-next",
  "provider",
  "library",
  "downloads",
  "notifications",
  "history",
  "download",
  "details",
  "setup",
  "settings",
  "trending",
  "toggle-mode",
  "diagnostics",
  "help",
  "menu",
  "quit",
] as const satisfies readonly AppCommandId[];
